version: '2'

services:
  api:
    build: .
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    links:
      - redis:redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://estrenos-cache
    container_name: estrenos-api

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - .env
    container_name: estrenos-cache
